package com.ankki.druid.parser;

import com.alibaba.druid.DbType;


/**
 * b07-dbType
 */
public enum DbTypeEnum {

    SQLSERVER(Integer.valueOf(1), DbType.sqlserver, "SQLSERVER"),
    MySQL(Integer.valueOf(2), DbType.mysql, "MySQL"),
    oracle(Integer.valueOf(3), DbType.oracle, "Oracle"),
    Sybase(Integer.valueOf(4), DbType.sybase, "Sybase"),
    DB2(Integer.valueOf(5), DbType.db2, "DB2"),
    Informix(Integer.valueOf(6), DbType.informix, "Informix"),
    PostgreSQL(Integer.valueOf(7), DbType.postgresql, "PostgreSQL"),
    cache(Integer.valueOf(8), null, "Cach"),
    Samba(Integer.valueOf(9), null, "Samba"),
    Cache_Portal(Integer.valueOf(10), null, "Cach"),
    Http(Integer.valueOf(11), null, "Http"),
    DMDbms(Integer.valueOf(12), DbType.dm, "DMDbms"),
    Kingbase(Integer.valueOf(13), DbType.kingbase, "Kingbase"),
    Gbase(Integer.valueOf(14), DbType.gbase, "Gbase"),
    FTP(Integer.valueOf(15), null, "FTP"),
    POP3(Integer.valueOf(16), null, "POP3"),
    SMTP(Integer.valueOf(17), null, "SMTP"),
    middleware(Integer.valueOf(18), null, "middleware"),
    Hive(Integer.valueOf(19), DbType.hive, "Hive"),
    IP21_WEBSERVICE(Integer.valueOf(20), null, "IP21_WEBSERVICE"),
    IP21_API(Integer.valueOf(21), null, "IP21_API"),
    NFS(Integer.valueOf(22), null, "NFS"),
    HIVE_VIEW(Integer.valueOf(23), null, "HIVE_VIEW"),
    SOLR(Integer.valueOf(24), null, "SOLR"),
    HBASE_JAVA_API(Integer.valueOf(25), null, "HBASE_JAVA_API"),
    HWI(Integer.valueOf(26), null, "HWI"),
    MongoDB(Integer.valueOf(27), null, "MongoDB"),
    REDIS(Integer.valueOf(28), null, "REDIS"),
    ShenTong(Integer.valueOf(29), null, ""),
    telnet(Integer.valueOf(30), null, "telnet"),
    HANA(Integer.valueOf(32), null, "HANA"),
    T_SSH(Integer.valueOf(33), null, "T_SSH"),
    RECORD_HIVE(Integer.valueOf(34), null, "RECORD_HIVE"),
    HIVE_HSQL(Integer.valueOf(36), null, "HIVE_HSQL"),
    ES(Integer.valueOf(37), DbType.elastic_search, "ES"),
    GaussDB(Integer.valueOf(38), DbType.gaussdb, "GaussDB"),
    LibrA(Integer.valueOf(39), null, "LibrA"),
    MariaDB(Integer.valueOf(40), DbType.mariadb, "MariaDB"),
    HBASE_SHELL(Integer.valueOf(41), null, "HBASE_SHELL"),
    XUGU(Integer.valueOf(42), DbType.xugu, "XUGU"),
    OpenPlant(Integer.valueOf(43), null, "OpenPlant"),
    Impala(Integer.valueOf(50), DbType.impala, "Impala"),
    UXDB(Integer.valueOf(51), null, "UXDB"),
    DorisDB(Integer.valueOf(52), DbType.doris, "DorisDB"),
    Deepgreen(Integer.valueOf(53), null, "Deepgreen DB"),
    Greenplum(Integer.valueOf(54), DbType.greenplum, "Greenplum"),
    Highgo(Integer.valueOf(55), DbType.highgo, "Highgo"),
    TiDB(Integer.valueOf(56), DbType.tidb, "TiDB"),
    IRIS(Integer.valueOf(57), null, "IRIS"),
    Cache_Telnet(Integer.valueOf(58), null, "Cach"),
    HTTPS(Integer.valueOf(61), null, "HTTPS"),
    Https_Portal(Integer.valueOf(62), null, "HTTPS_PORTAL"),
    IRIS_Portal_https(Integer.valueOf(62), null, "IRIS_Portal_https"),
    IRIS_Telnet(Integer.valueOf(64), null, "IRIS_Telnet"),
    IRIS_Portal_http(Integer.valueOf(65), null, "IRIS_Portal_http"),
    ClickHouse_Client(Integer.valueOf(70), null, "ClickHouse_Client"),
    ClickHouse(Integer.valueOf(71), DbType.clickhouse, "ClickHouse"),
    Teradata(Integer.valueOf(91), DbType.teradata, "Teradata"),
    TDSQL_MySQL(Integer.valueOf(92), null, "TDSQL_MySQL"),
    TDSQL_PostgreSQL(Integer.valueOf(93), null, "TDSQL_PostgreSQL"),
    OceanBase_MySQL(Integer.valueOf(94), DbType.oceanbase, "OceanBase_MySQL"),
    OceanBase_Oracle(Integer.valueOf(95), DbType.oceanbase_oracle, "OceanBase_Oracle"),
    Vastbase(Integer.valueOf(98), null, "Vastbase"),
    ALI_RDS_MySQL(Integer.valueOf(2001), null, "ALI_RDS_MySQL"),
    Argo(Integer.valueOf(99), null, "Argo"),
    Starrocks(Integer.valueOf(100), DbType.starrocks, "Starrocks"),
    ArteryBase(Integer.valueOf(101), null, "ArteryBase"),
    Hudi(Integer.valueOf(103), null, "Hudi"),
    Kudu(Integer.valueOf(104), null, "Kudu"),
    PolarDB_MySQL(Integer.valueOf(105), null, "PolarDB_MySQL"),
    PolarDB_PostgreSQL(Integer.valueOf(106), null, "PolarDB_PostgreSQL"),
    Kafka(Integer.valueOf(107), null, "Kafka"),
    Seabox(Integer.valueOf(109), null, "Seabox"),
    Hdfs(Integer.valueOf(110), null, "Hdfs"),
    Hdfs_Http(Integer.valueOf(111), null, "Hdfs_Http"),
    IoTDB(Integer.valueOf(112), null, "IoTDB"),
    K_DB(Integer.valueOf(114), null, "K-DB"),
    Yashan(Integer.valueOf(115), null, "Yashan"),
    InfluxDB(Integer.valueOf(116), null, "InfluxDB"),
    PerconaServer(Integer.valueOf(117), DbType.mysql, "PerconaServer"),
    AliSQL(Integer.valueOf(118), DbType.mysql, "AliSQL"),
    WebScaleSQL(Integer.valueOf(119), DbType.mysql, "WebScaleSQL"),
    InnoSQL(Integer.valueOf(120), DbType.mysql, "InnoSQL"),
    CascaDB(Integer.valueOf(121), DbType.mysql, "CascaDB"),
    Cotton(Integer.valueOf(122), DbType.mysql, "Cotton"),
    MyRocks(Integer.valueOf(123), DbType.mysql, "MyRocks"),
    Drizzle(Integer.valueOf(124), DbType.mysql, "Drizzle"),
    TokuDB(Integer.valueOf(125), DbType.mysql, "TokuDB"),
    XtraDB(Integer.valueOf(126), DbType.mysql, "XtraDB"),
    SpiderForMySQL(Integer.valueOf(127), DbType.mysql, "SpiderForMySQL"),
    MyRelay(Integer.valueOf(128), DbType.mysql, "MyRelay"),
    MySQLMaria(Integer.valueOf(129), DbType.mysql, "MySQLMaria"),
    MepSQL(Integer.valueOf(130), DbType.postgresql, "MepSQL"),
    Mroonga(Integer.valueOf(131), DbType.mysql, "Mroonga"),
    MySQLEnterprise(Integer.valueOf(132), DbType.mysql, "MySQLEnterprise"),
    OurDelta(Integer.valueOf(133), DbType.mysql, "OurDelta"),
    OQGRAPH(Integer.valueOf(134), DbType.mysql, "OQGRAPH"),
    AsterData(Integer.valueOf(135), DbType.teradata, "AsterData"),
    BDR(Integer.valueOf(136), DbType.postgresql, "BDR"),
    GresCube(Integer.valueOf(137), DbType.postgresql, "GresCube"),
    izgres(Integer.valueOf(138), DbType.postgresql, "izgres"),
    Citus(Integer.valueOf(139), DbType.postgresql, "Citus"),
    CyberCluster(Integer.valueOf(140), DbType.postgresql, "CyberCluster"),
    ExtenDB(Integer.valueOf(141), DbType.postgresql, "ExtenDB"),
    FUJITSUEnterprisePG(Integer.valueOf(142), DbType.postgresql, "FUJITSUEnterprisePG"),
    Vertica(Integer.valueOf(143), null, "Vertica"),
    GridSQL(Integer.valueOf(144), DbType.postgresql, "GridSQL"),
    GreatBridgePG(Integer.valueOf(145), DbType.postgresql, "GreatBridgePG"),
    HadoopDB(Integer.valueOf(146), null, "HadoopDB"),
    Hadapt(Integer.valueOf(147), null, "Hadapt"),
    Mammoth(Integer.valueOf(148), DbType.mysql, "Mammoth"),
    Netezza(Integer.valueOf(149), DbType.postgresql, "Netezza"),
    NuSphereUltraSQL(Integer.valueOf(150), DbType.postgresql, "NuSphereUltraSQL"),
    ParAccel(Integer.valueOf(151), DbType.postgresql, "ParAccel"),
    PervasivePostgreSQL(Integer.valueOf(152), DbType.postgresql, "PervasivePostgreSQL"),
    PGCluster(Integer.valueOf(153), DbType.postgresql, "PGCluster"),
    PGClusterII(Integer.valueOf(154), DbType.postgresql, "PGClusterII"),
    PGPoolII(Integer.valueOf(155), DbType.postgresql, "PGPoolII"),
    PipelineDB(Integer.valueOf(156), DbType.postgresql, "PipelineDB"),
    PostgresForest(Integer.valueOf(157), DbType.postgresql, "PostgresForest"),
    PostgresPlus(Integer.valueOf(158), DbType.postgresql, "PostgresPlus"),
    PostgresXC(Integer.valueOf(159), DbType.postgresql, "PostgresXC"),
    StadoPostgresPlusAdvancedServer(Integer.valueOf(160), DbType.postgresql, "StadoPostgresPlusAdvancedServer"),
    PostgresR(Integer.valueOf(161), DbType.postgresql, "PostgresR"),
    PostgresX2(Integer.valueOf(162), DbType.postgresql, "PostgresX2"),
    RecDB(Integer.valueOf(163), DbType.postgresql, "RecDB"),
    RedShift(Integer.valueOf(164), DbType.postgresql, "RedShift"),
    PostgresXL(Integer.valueOf(165), DbType.postgresql, "PostgresXL"),
    PowerGres(Integer.valueOf(166), DbType.postgresql, "PowerGres"),
    PowerGresPlus(Integer.valueOf(167), DbType.postgresql, "PowerGresPlus"),
    PostgreSQLForSolaris(Integer.valueOf(168), DbType.postgresql, "PostgreSQLForSolaris"),
    ToroDB(Integer.valueOf(169), DbType.postgresql, "ToroDB"),
    RedHatDatabase(Integer.valueOf(170), null, "RedHatDatabase"),
    TelegraphCQ(Integer.valueOf(171), DbType.postgresql, "TelegraphCQ"),
    TruCQ(Integer.valueOf(172), DbType.postgresql, "TruCQ"),
    YahooEverest(Integer.valueOf(173), DbType.postgresql, "YahooEverest"),
    VerticalPartitioningForMySQL(Integer.valueOf(174), DbType.mysql, "VerticalPartitioningForMySQL"),
    MinIO(Integer.valueOf(175), null, "MinIO");


    private Integer id;

        private DbType dbType;

        private String name;


        DbTypeEnum(Integer id, DbType dbType, String name) {
            this.id = id;
            this.dbType = dbType;
            this.name = name;
        }
}


